### ISSUE TITLE
Tag services with correct release tag

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/weco-deploy#55]
Given releases `release1` and `release2` for `service`, where there is no diff in the images of those releases.

* `release1` is prepared and deployed
* `service` gets tagged with `deployment:label=release1`
* `release2` is prepared and deployed
* `service` and its tasks doesn't get retagged 

This is because if there is not diff in the images [we `noop` the release](https://github.com/wellcomecollection/weco-deploy/blob/master/src/deploy/ecr.py#L143)

Thus [the service doesn't get deployed](https://github.com/wellcomecollection/weco-deploy/blob/master/src/deploy/project.py#L390) and thus not tagged.

This is confusing as the release that is updated in Dynamo is `release2` as is all the logging.

The reason for this is for long running tasks (storage service especially) - if we kill a task after an hours work, only to spin up the same task we are losing hours of work for nothing.

Thoughts are
* we tag the service and tasks without a redeploy
* ...

**Comment by kenoir** [comment]
Closing as resolved.
